### ISSUE TITLE
[Idea] Ability to add links to countdown for more information

### ISSUE THREAD

**Issue by thechantaro** [Mavulp/countdown#2]
How about adding the ability to add links to a countdown, like a google doc of a specific meetup

**Comment by zealsprince** [comment]
Added `link` column to the database table for events!

**Comment by dolanske** [comment]
I will close this as completed, because the data contains it. Although the countdown website will not utilize it, the upcoming Hivecom website will have its own event list which this website will link to. There all events will have all their metadata shown properly.
